### ISSUE TITLE
First release considerations and tasks

### ISSUE THREAD

**Issue by HarryTWhite** [EXA-UQ/EXAUQ-Toolbox#324]
### Motivation
-----------------
In preparation for the first release there are a number of admin/documentation tasks that need to be sorted in order for things to run smoothly and ensure that the toolbox can be more easily maintained once in the public viewing. This is currently an issue which will act as an overview for a sort of release epic to check things off but without overloading issues at the moment. Please feel free to add anything that has been missed (@JSalter90 @mbjohns) and needs to be sorted pre-release.

### Acceptance Criteria
-------------------------
**Repository:**

These are tasks that relate to the general maintenance, location and admin for the GitHub repository itself.

- [x] Exeter Innovation to check regarding public repo - have the licence ready (**JS/PC**). 
- [x] Decide on location of public repository and forking (ideally outstanding issues transfer over!). (**TEAM**)
- [x] Permissions for both maintenance team alongside public contributors. (**MJ**)
- [x] Add licencing - see iss #327 and PR #328 
- [x] Check there is no sensitive information in commits (may need to be squashed if so!) (**HW**)
- [x] Write a code of conduct for new contributors. - see iss #327 and PR #328  (**HW**)
- [x] Ensure ReadMe and download instructions are up to date. - see iss #327 and PR #328 (**HW**)
- [x] Tidy up stale branches/issues etc. (**MJ/HW**)
- [ ] Roadmap - what lies within scope for public contributors, when do they fork off etc. (This will all need to be explained
in either a Contributing page or a separate roadmap page. (**TEAM**) (**Note: To be moved to pre-march handover**)
- [ ] Add repo badges for test coverage/documentation etc. to maintain credibility of toolbox (**MJ**)

**Documentation:**

These are tasks relating to the documentation of the code and toolbox. This will need to be reviewed by the researchers pre-release to ensure that the scope of the toolbox is documented as expected. 

- [ ] Tidy API Documentation. See iss #275 and PR #321 (**HW**)
- [x] Correct initial tutorials and guides (with the opportunity to add more). see issues #331 and #267  (**TEAM**)
- [x] Upload to GitHub pages (or equivalent) with workflow to update on new release. See iss #289 (**MJ/HW**)
- [x] Introduce a guide for how to document new code alongside styles/conventions to follow for new contributors. See iss #327 and PR #328 (**HW**)
- [ ] Consider (eventually) JOSS? (**TEAM**) (**Note: To be moved to pre-march handover**)

**Maintenance of Code:**

These are the tasks that will aid the maintenance of the code and contributions to the code once the toolbox becomes public and particularly once the RSE team fully hand over.  

- [x] Check/Create GitHub workflows including (but not limited to): tests, package dependencies, linting, docs building. See iss #315 and PR #341 (**MJ/HW**) 
- [x] Create guide for contributors (alongside documentation styling) for code expectations and the new code process including (but not limited to), creating issues, PRs and review expectations etc.  See iss #327 and PR #328 (**HW**)
- [x] Make Python 3.13 compatible. (**MJ/HW**)
- [ ] Consider getting in touch with Turing to establish idea of current maintenance of `mogp-emulator` (**MJ**)
